In [1]:
# ============================================
# Sales Analytics Dashboard
# Phase 1 : Data Understanding
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("Libraries Imported Successfully ✅")

Libraries Imported Successfully ✅

In [2]:
df = pd.read_csv("../data/raw/superstore_sales.csv")

print("Dataset Loaded Successfully ✅")

Dataset Loaded Successfully ✅

In [3]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD100001,2025-07-12,2025-07-13,Same Day,CUST1130,Customer 123,Consumer,USA,New York,New York,38657,East,PROD338,Technology,Accessories,Accessories Model 617,860.76,4,0.05,52.29
1,ORD100002,2024-01-07,2024-01-14,Second Class,CUST3859,Customer 1732,Corporate,USA,Philadelphia,Pennsylvania,46421,East,PROD259,Furniture,Bookcases,Bookcases Model 320,2648.83,9,0.15,441.77
2,ORD100003,2024-02-14,2024-02-20,Same Day,CUST3196,Customer 512,Corporate,USA,Houston,Texas,20328,South,PROD665,Furniture,Tables,Tables Model 400,2293.72,2,0.10,438.37
3,ORD100004,2024-03-22,2024-03-29,Second Class,CUST4549,Customer 414,Corporate,USA,Miami,Florida,46434,South,PROD564,Furniture,Bookcases,Bookcases Model 750,1997.34,2,0.00,563.09
4,ORD100005,2025-10-25,2025-10-26,Second Class,CUST3187,Customer 2987,Consumer,USA,Houston,Texas,31417,South,PROD573,Office Supplies,Paper,Paper Model 488,1162.36,4,0.30,245.25

In [4]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 15000
Columns : 20

In [5]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       15000 non-null  str
 1   Order Date     15000 non-null  str
 2   Ship Date      15000 non-null  str
 3   Ship Mode      15000 non-null  str
 4   Customer ID    15000 non-null  str
 5   Customer Name  15000 non-null  str
 6   Segment        15000 non-null  str
 7   Country        15000 non-null  str
 8   City           15000 non-null  str
 9   State          15000 non-null  str
 10  Postal Code    15000 non-null  int64
 11  Region         15000 non-null  str
 12  Product ID     15000 non-null  str
 13  Category       15000 non-null  str
 14  Sub-Category   15000 non-null  str
 15  Product Name   15000 non-null  str
 16  Sales          15000 non-null  float64
 17  Quantity       15000 non-null  int64
 18  Discount       15000 non-null  float64
 19  Profit         15000 non-null  float64
dtypes: float64(3), int64(2), str(15)
memory usage: 2.3 MB

In [7]:
df.describe()

        Postal Code         Sales      Quantity      Discount        Profit
count  15000.000000  15000.000000  15000.000000  15000.000000  15000.000000
mean   54705.754733   3620.159042      5.483200      0.132787    547.910345
std    25998.846331   3007.031644      2.871539      0.098492    654.019451
min    10005.000000     18.980000      1.000000      0.000000   -614.500000
25%    32160.250000   1168.230000      3.000000      0.050000     97.007500
50%    54223.500000   2755.905000      6.000000      0.150000    314.595000
75%    77165.750000   5355.425000      8.000000      0.200000    773.202500
max    99989.000000  14942.930000     10.000000      0.300000   5080.580000

In [8]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
print("Unique Categories :", df["Category"].unique())
print()
print("Unique Regions :", df["Region"].unique())
print()
print("Unique Segments :", df["Segment"].unique())

Unique Categories : <StringArray>
['Technology', 'Furniture', 'Office Supplies']
Length: 3, dtype: str

Unique Regions : <StringArray>
['East', 'South', 'West', 'Central']
Length: 4, dtype: str

Unique Segments : <StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str