In [1]:
# ============================================
# Sales Analytics Dashboard
# Phase 2 : Data Cleaning
# ============================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully ✅")

Libraries Imported Successfully ✅

In [2]:
df = pd.read_csv("../data/raw/superstore_sales.csv")

print("Dataset Loaded Successfully ✅")

Dataset Loaded Successfully ✅

In [3]:
sales_df = df.copy()

In [4]:
sales_df.isnull().sum()
missing = sales_df.isnull().sum()

missing_percent = (
    missing / len(sales_df) * 100
).round(2)

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percent
})

missing_df

               Missing Values  Percentage
Order ID                    0         0.0
Order Date                  0         0.0
Ship Date                   0         0.0
Ship Mode                   0         0.0
Customer ID                 0         0.0
Customer Name               0         0.0
Segment                     0         0.0
Country                     0         0.0
City                        0         0.0
State                       0         0.0
Postal Code                 0         0.0
Region                      0         0.0
Product ID                  0         0.0
Category                    0         0.0
Sub-Category                0         0.0
Product Name                0         0.0
Sales                       0         0.0
Quantity                    0         0.0
Discount                    0         0.0
Profit                      0         0.0

In [5]:
duplicates = sales_df.duplicated().sum()

print("Duplicate Rows :", duplicates)

sales_df.drop_duplicates(inplace=True)

Duplicate Rows : 0

In [6]:
sales_df.dtypes

Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [9]:
sales_df["Order Date"] = pd.to_datetime(
    sales_df["Order Date"]
)

sales_df["Ship Date"] = pd.to_datetime(
    sales_df["Ship Date"]
)
sales_df.dtypes

Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [10]:
numeric_cols = [
    "Sales",
    "Profit",
    "Quantity",
    "Discount"
]

sales_df[numeric_cols].describe()

              Sales        Profit      Quantity      Discount
count  15000.000000  15000.000000  15000.000000  15000.000000
mean    3620.159042    547.910345      5.483200      0.132787
std     3007.031644    654.019451      2.871539      0.098492
min       18.980000   -614.500000      1.000000      0.000000
25%     1168.230000     97.007500      3.000000      0.050000
50%     2755.905000    314.595000      6.000000      0.150000
75%     5355.425000    773.202500      8.000000      0.200000
max    14942.930000   5080.580000     10.000000      0.300000

In [13]:
sales_df[sales_df["Sales"] < 0]
sales_df[sales_df["Quantity"] <= 0]
sales_df[sales_df["Discount"] > 1]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [14]:
Q1 = sales_df["Sales"].quantile(0.25)
Q3 = sales_df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = sales_df[
    (sales_df["Sales"] < lower) |
    (sales_df["Sales"] > upper)
]

print(outliers.shape)

(244, 20)

In [16]:
sales_df["Order Year"] = (
    sales_df["Order Date"].dt.year
)
sales_df["Order Month"] = (
    sales_df["Order Date"].dt.month_name()
)
sales_df["Quarter"] = (
    sales_df["Order Date"].dt.quarter
)
sales_df["Delivery Days"] = (
    sales_df["Ship Date"] -
    sales_df["Order Date"]
).dt.days
sales_df["Profit Margin"] = (
    sales_df["Profit"] /
    sales_df["Sales"]
) * 100

In [17]:
sales_df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Quarter,Delivery Days,Profit Margin
0,ORD100001,2025-07-12,2025-07-13,Same Day,CUST1130,Customer 123,Consumer,USA,New York,New York,38657,East,PROD338,Technology,Accessories,Accessories Model 617,860.76,4,0.05,52.29,2025,July,3,1,6.074864
1,ORD100002,2024-01-07,2024-01-14,Second Class,CUST3859,Customer 1732,Corporate,USA,Philadelphia,Pennsylvania,46421,East,PROD259,Furniture,Bookcases,Bookcases Model 320,2648.83,9,0.15,441.77,2024,January,1,7,16.677930
2,ORD100003,2024-02-14,2024-02-20,Same Day,CUST3196,Customer 512,Corporate,USA,Houston,Texas,20328,South,PROD665,Furniture,Tables,Tables Model 400,2293.72,2,0.10,438.37,2024,February,1,6,19.111749
3,ORD100004,2024-03-22,2024-03-29,Second Class,CUST4549,Customer 414,Corporate,USA,Miami,Florida,46434,South,PROD564,Furniture,Bookcases,Bookcases Model 750,1997.34,2,0.00,563.09,2024,March,1,7,28.191995
4,ORD100005,2025-10-25,2025-10-26,Second Class,CUST3187,Customer 2987,Consumer,USA,Houston,Texas,31417,South,PROD573,Office Supplies,Paper,Paper Model 488,1162.36,4,0.30,245.25,2025,October,4,1,21.099315

In [18]:
sales_df.to_csv(
    "../data/cleaned/clean_sales_data.csv",
    index=False
)

print("Clean dataset saved successfully! ✅")

Clean dataset saved successfully! ✅